registered_domain_name = "my.domain"
subdomains             = ["www", "test"]
# route53_hosted_zone_id = "TESTZONE" # leave empty string to create a zone
# apigw_endpoint_url = # no need to define for first time setup
ghactions_aws_role_arn = "ARN_GHActions_Role"
acm_certificate_arn    = "arn:aws:acm:us-east-1:094625812543:certificate/test"
aws_region             = "us-east-1"
# aws_profile            = "123456789012_AccessRole"
aws_role_arn = "aws:arn:1234:abcd"
is_prod_build          = false # sets up test mode, builds own route53 zone