aws_region            = "us-east-1"
aws_profile           = "123456_MyAccessProfiile"
my_terraform_org = "TerraformOrgName"
terraform_workspace = "tf-workspace"
terraform_project_name = "test-project"