name: Deploy static site to AWS S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  id-token: write
  contents: read


env:
  GITHUB_SRC_FOLDER: '' # GitHub folder to sync to AWS ( e.g: prod/ ), if sync from root folder, enter ''


jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest

    steps:
    - name: checks out this repo 
      uses: actions/checkout@v3


    - name: get temporary AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.S3_BUCKET_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
        role-session-name: GHASession-anthony_cloud_resume
        unset-current-credentials: true
        retry-max-attempts: 3
        output-credentials: true

        
    - name: verify temp credentials validity
      run: |
        aws sts get-caller-identity


    - name: sync files to aws s3
      shell: bash
      # run: |
        # aws s3 sync ./site/ s3://${{ secrets.S3_BUCKET_NAME }} --follow-symlinks
      run: |
        aws s3 sync ./${{ env.GITHUB_SRC_FOLDER }} s3://${{ secrets.S3_BUCKET_NAME }} --follow-symlinks

        
