name: Deploy static site to AWS S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: checks out this repo


    - name: get temporary AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      id: step_aws_creds
      with:
        aws-region: ${{ secrets.S3_BUCKET_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
        role-session-name: GHASession-anthony_cloud_resume
        unset-current-credentials: true
        retry-max-attempts: 3
        output-credentials: true

        
    - name: get caller identity 1
      run: |
        aws sts get-caller-identity


    - name: S3 sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --follow-symlinks --exclude '.git/*' --exclude '.github/*' --exclude 'README.md'
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ steps.step_aws_creds.outputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.step_aws_creds.outputs.aws-secret-access-key }}
        AWS_REGION:  ${{ secrets.S3_BUCKET_REGION }}
        SOURCE_DIR: 'site'
