name: Publish Slack integration Lambda

on:
    push:
        branches: ["terraform"]
        paths: ["aws/sendSlackMessage/**"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    call-package-lambda-workflow:
        runs-on: ubuntu-latest

        steps:
            - name: check out repo
              uses: actions/checkout@v3

            - name: zips Lambda code and upload to AWS
              uses: ~/.github/workflows/package-n-deploy-lambda.yml

            #   secrets: inherit

              with:
                lambda_source_folder-name: sendSlackMessage

                output-zipped_file_name: sendSlackMessage.zip

                lambda_function_arn: ${{ secrets.SLACK_INTEGRATION_LAMBDA_ARN }}
