name: Deploy Lambda for visitor counter to AWS

on:
    push:
        branches: ["main", "lambda-unittest"]
        paths: ["back_end/**"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test-lambda-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: check out repo
              uses: actions/checkout@v3

            - name: create default aws config for unittest
              run: |
                echo "[default]" >> ~/.aws/config
echo "aws_access_key_id=test" >> ~/.aws/config
echo "aws_secret_access_key=test" >> ~/.aws/config

            - name: install python dependencies
              run: |
                pip3 install -r requirements.txt

            - name: run Python unittest
              run: |
                python3 -m unittest