name: Terraform destroy w/ manual approval

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write

jobs:
  empty-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: get temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_STACK_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
          role-session-name: GHASession-anthony_cloud_resume
          unset-current-credentials: true
          retry-max-attempts: 3
          output-credentials: true

      
      - name: verify temp credentials validity
        run: |
          aws sts get-caller-identity

      - name: empty frontend S3 bucket
        run: |
          aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }} --recursive



  destroy-terraform-infrastructure:
    needs: [ empty-s3-bucket ]
    uses: ./.github/workflows/terraform-update-infrastructure.yml

    with:
      destroy-terraform: true

    secrets: inherit