name: Terraform destroy w/ manual approval

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  id-token: write

jobs:
  empty-s3-bucket:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: get temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.MANUAL_AWS_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }} 
          role-session-name: GHASession-anthony_cloud_resume
          unset-current-credentials: true
          retry-max-attempts: 3
          output-credentials: true

      
      - name: verify temp credentials validity
        run: |
          aws sts get-caller-identity

      - name: empty frontend S3 bucket
        run: |
          echo Deleting objects
          aws s3api delete-objects --bucket ${{ secrets.AWS_S3_BUCKET_NAME }} --delete "$(aws s3api list-object-versions --bucket ${{ secrets.AWS_S3_BUCKET_NAME }} --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')"

          echo Deleting markers
          aws s3api delete-objects --bucket ${{ secrets.AWS_S3_BUCKET_NAME }} --delete "$(aws s3api list-object-versions --bucket ${{ secrets.AWS_S3_BUCKET_NAME }} --query='{Objects: DeleteMarkers[].{Key:Key,VersionId:VersionId}}')"


  destroy-terraform-infrastructure:
    needs: [ empty-s3-bucket ]
    uses: ./.github/workflows/terraform-update-infrastructure.yml

    with:
      destroy-terraform: true

    secrets: inherit

  
  
  reset-repo-secrets-n-variables:
    needs: [ destroy-terraform-infrastructure ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Reset repo secrets & variables
        env:
          GH_TOKEN: ${{ secrets.MANUAL_GITHUB_PERSONAL_ACCESS_TOKEN }}
        run: |
          gh secret set AWS_CLOUDFRONT_DISTRIBUTION_ID --body "reset"
          gh secret set AWS_GITHUB_ROLE_ARN --body "reset"
          gh secret set AWS_S3_BUCKET_NAME --body "reset"
          gh secret set AWS_SLACK_INTEGRATION_LAMBDA_ARN --body "reset"
          gh secret set AWS_VISITOR_COUNTER_LAMBDA_ARN --body "reset"
          gh variable set VISITOR_COUNTER_API_INVOKE_URL --body "reset" 