name: Terraform destroy w/ manual approval

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write

jobs:
  destroy:
    uses: ./.github/workflows/terraform-update-infrastructure.yml

    with:
      destroy-terraform: true

    secrets: inherit